import './globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script';
import React, {useEffect} from "react";
import TelegramProvider from "@/src/components/TelegramProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Script src="https://telegram.org/js/telegram-web-app.js" />
      <body className={inter.className}>
      {children}
      </body>
    </html>
  )
}
